import "./globals.css";
import Navbar from "./components/navbar";
import type { ReactNode } from "react";

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="es">
      <body className="bg-white text-black">
        <Navbar />

        <main className="p-6">
          {children}
        </main>
      </body>
    </html>
  );
}
// export const metadata: Metadata = {
//   title: "Simulación Inventario",
//   description: "Generated by Nath™",
// };


